### PR TITLE
Integration with Gradle

### PR DESCRIPTION
**Pull request by kshchepanovskyi**
With [gradle](http://gradle.org/) and [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin) we can build JetBrains plugins without doing manual work in the IDE.
Plugin takes care about downloading IntelliJ IDEA distribution and source code, and allows you to start IntelliJ IDEA with your plugin enabled by a single command.

Compilation:
```
./gradlew build
```

Upload to [bintray](https://bintray.com/antlr/maven):
```
./gradlew bintrayUpload
```

### CODE REVIEW

**Comment by kshchepanovskyi** [comment]
@parrt 

As far as I understand there is no easy way to build IntelliJ IDEA plugins using maven. With gradle it is relatively easy. 

Jetbrains supports a plugin for gradle, and they recommend it as a better way of building plugins: 
* https://github.com/JetBrains/gradle-intellij-plugin
* http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system.html

Pull request for sample plugin project is not ready yet, most probably I will finish it in next few days. But this part is ready, and it would be nice if somebody can already review it.

**Comment by kshchepanovskyi** [comment]
There are two problems with sample plugin.
First, it does not compile, parent class does not have a constructor with one argument:
```java
public class VardefSubtree extends IdentifierDefSubtree {
	public VardefSubtree(@NotNull ASTNode node) {
		super(node);
	}
}
```
Second - I tried to fix compilation by passing `SampleParserDefinition.ID` as a second arg (the most suitable fix according to 57db94ac49ddb5eeb674b6e9b71d936037223f94), but now unit tests are failing.

Changes: https://github.com/kshchepanovskyi/jetbrains-plugin-sample/commit/af783a008e483f4816e770424f773c53028599ef

`./gradlew build` should be enough to reproduce this issue.

**Comment by kshchepanovskyi** [comment]
Added tests for `XPath` (failing) from https://github.com/antlr/jetbrains-plugin-sample
As `XPath` is defined in this project, it should be tested here too.

**Comment by kshchepanovskyi** [comment]
http://jenkins.ksprojects.org/view/antlr/job/antlr-jetbrains-adapter/1/console

```
org.antlr.jetbrains.adaptor.xpath.XPathTest > testAnyVarDef FAILED
    junit.framework.ComparisonFailure at XPathTest.java:197
org.antlr.jetbrains.adaptor.xpath.XPathTest > testSingleVarDef FAILED
    junit.framework.ComparisonFailure at XPathTest.java:197
org.antlr.jetbrains.adaptor.xpath.XPathTest > testAllVarDefIDsInScopes FAILED
    junit.framework.ComparisonFailure at XPathTest.java:197
org.antlr.jetbrains.adaptor.xpath.XPathTest > testTopLevelVarDefIDsInScopes FAILED
    junit.framework.ComparisonFailure at XPathTest.java:197
org.antlr.jetbrains.adaptor.xpath.XPathTest > testMultiVarDef FAILED
    junit.framework.ComparisonFailure at XPathTest.java:197
org.antlr.jetbrains.adaptor.xpath.XPathTest > testVarDefIDs FAILED
    junit.framework.ComparisonFailure at XPathTest.java:197
org.antlr.jetbrains.adaptor.xpath.XPathTest > testRuleUnderWildcard FAILED
    junit.framework.ComparisonFailure at XPathTest.java:197

12 tests completed, 7 failed
```

**Comment by kshchepanovskyi** [comment]
Looks like `SampleLanguage.g4` grammar is not full. Global vardefs are not fully supported.

For given source:

```
var q = 8
func f(x:[]) {}
var z = 9
```

We will get following output:

```
  ---->  DUMMY_BLOCK
========================================
var q = 8

func f(x:[]) {}

var z = 9  ---->  script
========================================
var q = 8  ---->  vardef
========================================
var  ---->  'var'
========================================
q  ---->  ID
========================================
=  ---->  '='
========================================
8  ---->  expr
========================================
8  ---->  primary
========================================
8  ---->  INT
========================================
func f(x:[]) {}  ---->  function
========================================
func  ---->  'func'
========================================
f  ---->  ID
========================================
(  ---->  '('
========================================
x:[]  ---->  formal_args
========================================
x:[]  ---->  formal_arg
========================================
x  ---->  ID
========================================
:  ---->  ':'
========================================
[]  ---->  type
========================================
[  ---->  '['
========================================
]  ---->  ']'
========================================
)  ---->  ')'
========================================
{}  ---->  block
========================================
{  ---->  '{'
========================================
}  ---->  '}'
========================================
var  ---->  ERROR_ELEMENT
========================================
var  ---->  'var'
========================================
z = 9  ---->  statement
========================================
z  ---->  ID
========================================
=  ---->  '='
========================================
9  ---->  expr
========================================
9  ---->  primary
========================================
9  ---->  INT
========================================
```

Second `var` is recognized as an `ERROR_ELEMENT`.

Output generated by adding two lines into [Trees#_findAllNodes](https://github.com/antlr/jetbrains/blob/58b14dcad00feae472c03255008d9cb9b5d98b6f/src/org/antlr/jetbrains/adaptor/psi/Trees.java#L125)

```java
	public static void _findAllNodes(PsiElement t, int index, boolean findTokens,
									 List<? super PsiElement> nodes)
	{
		System.out.println(t.getText() + "  ---->  " + t.getNode().getElementType());
		System.out.println("========================================");
		// check this node (the root) first
		// ...
```

**Comment by kshchepanovskyi** [comment]
Final unit test: https://github.com/kshchepanovskyi/jetbrains/blob/gradle-integration/src/test/java/org/antlr/jetbrains/SampleParserTest.java

For `func x(){} var a = 9` it gives:

```
line 1:11 extraneous input 'var' expecting {<EOF>, '{', 'if', 'while', 'return', 'print', 'func', ID}
```

**Comment by kshchepanovskyi** [comment]
Fixed all unit tests: https://github.com/antlr/jetbrains/pull/7/commits/8b60f29e5f9bc1227dc766bbc54f00838addc537

Changed grammar (`script` rule) and fixed all xpath expressions, they were not up-to-date with grammar.

**Comment by kshchepanovskyi** [comment]
https://plugins.jetbrains.com/plugin/8277
@parrt : I already have few thousands users of my plugin, flight is normal :)

**Comment by parrt** [comment]
Heh, sounds great. I plan on hitting antlr, plugin stuff next week.

**Comment by kshchepanovskyi** [comment]
I cannot keep this PR open anymore, as there are conflicts already.
Instead, I will maintain my own fork - https://github.com/kshchepanovskyi/antlr-jetbrains-adapter
(there are some other things that I have to fix).

For now I'm closing it.

**Comment by bjansen** [comment]
@kshchepanovskyi why did you give up on this PR? It looks like your fork has multiple interesting changes that ought to be merged back into this repo. I think you deserve to become a commiter on this project for your involvement, wdyt @parrt ?

Having an unofficial repo that has more features than the 'official' repo is confusing, I was interested in using Gradle to build this project so I started doing the same thing @kshchepanovskyi already did, and when I came here to prepare my pull request I noticed by accident that someone else had already done it in his own fork :/

**Comment by kshchepanovskyi** [comment]
@bjansen 
I waited for half year before giving up on this PR :)

About merging changes from my fork back to the original repository - it might be tricky at this point of time.

**Pull request closed without merging**
